import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Online.module.css'
import NavBar from '@/componetns/minacu/navBar'
import 'bootstrap/dist/css/bootstrap.min.css' ;
import Navegacao from '@/componetns/minacu/navegar'
import Rodape from '@/componetns/minacu/rodape';
import FormCadastro from '@/componetns/minacu/formTelecom';
import TituloOnline from '@/componetns/tituloOnline';

const inter = Inter({ subsets: ['latin'] })

export default function Assinar() {
  return (
    <>
      <Head>
        <title>Integrato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div className= {styles['body']}>
      <Navegacao/>
      <TituloOnline/>
      <FormCadastro/>
      <Rodape/>
      </div>
    </>
  )
}