import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Contrate.module.css'
import NavBar from '@/componetns/palmeiropolis/navBar'
import  'bootstrap/dist/css/bootstrap.min.css' ;
import Navegacao from '@/componetns/palmeiropolis/navegar'
import Rodape from '@/componetns/palmeiropolis/rodape';
import Contrate from '@/componetns/contrateTitulo';
import IconCompra from '@/componetns/palmeiropolis/contrateIconFibra';

const inter = Inter({ subsets: ['latin'] })

export default function Plano() {
  return (
    <>
      <Head>
        <title>Integrato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div className= {styles['body']}>
      <Navegacao/>
      <Contrate/>
      <IconCompra/>
      <Rodape/>
      </div>
    </>
  )
}