import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/componets/palmeiropolis/navBar'
import  'bootstrap/dist/css/bootstrap.min.css' ;
import Navegacao from '@/componets/palmeiropolis/navegar'
import Rodape from '@/componets/rodape'
import Aplicativo from '@/componets/aplicativo'
import Botao from '@/componets/botao'
import BannerMeio from '@/componets/bannerMeio'
import Slide from '@/componets/slide'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Integratto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div className= {styles['body']}>
      <Navegacao/>
      <Aplicativo/>
      <BannerMeio/>
      <Slide/>
      <Rodape/>
      </div>
    </>
  )
}
